#!/bin/bash

set -e

#export PACKER_LOG=1
rm packer_virtualbox-iso_virtualbox.box || true
packer build -only virtualbox-iso ubuntu-16.04.1-server-amd64.json
vagrant box remove ubuntu-1604 || true
vagrant box add ubuntu-1604 packer_virtualbox-iso_virtualbox.box
