---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[manhattan::setup]
      - recipe[manhattan::setup_ruby-env]
      - recipe[manhattan::setup_mysql-env]
      - recipe[manhattan::setup_postgres-env]
      - recipe[manhattan::setup_redis-env]
      - recipe[manhattan::setup_mongodb-env]
      - recipe[manhattan::configure]
      - recipe[manhattan::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
