name 'manhattan'
maintainer 'Hiroshima ARC'
maintainer_email 'hiroshima.arc@gmail.com'
license 'all_rights'
description 'Installs/Configures martini'
long_description 'Installs/Configures martini'
version '1.1.0'

depends 'apt',    '2.9.2'
depends 'git', '~> 5.0.1'
depends 'tmux',   '~> 1.5.0'
depends 'mysql',  '~> 8.2.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'postgresql', '~> 6.0.1'
depends 'build-essential', '~> 7.0.1'
depends 'redis', '~> 3.0.4'
depends 'mongodb', '~> 0.16.2'
depends 'gin_and_bitters'
depends 'martini'
depends 'chef-dk','~> 3.0.0'
depends 'vagrant', '~> 0.7.0'