name 'manhattan'
maintainer 'Hiroshima ARC'
maintainer_email 'hiroshima.arc@gmail.com'
license 'all_rights'
description 'Installs/Configures martini'
long_description 'Installs/Configures martini'
version '0.1.0'

depends 'apt',    '2.6.1'
depends 'git', '~> 5.0.1'
depends 'tmux',   '~> 1.5.0'
depends 'mysql',  '~> 7.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'postgresql', '~> 4.0.6'
depends 'build-essential', '~> 7.0.1'
depends 'gin_and_bitters'
depends 'redis', '~> 3.0.4'