#!/bin/bash

set -e

#export PACKER_LOG=1
rm packer_virtualbox-iso_virtualbox.box || true
packer build -only virtualbox-iso ubuntu-14.04.3-server-amd64.json
vagrant box remove ubuntu-1404 || true
vagrant box add ubuntu-1404 packer_virtualbox-iso_virtualbox.box
