# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

script = <<SCRIPT
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", inline: script

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Every Vagrant virtual environment requires a box to build off of.
  #config.vm.box = "ubuntu/trusty64" #ubuntu14.4
  config.vm.box = "ubuntu/xenial64" #ubuntu16.4
  config.berkshelf.berksfile_path = nil
  config.berkshelf.enabled = true

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_zero" do |chef|
     chef.nodes_path = "nodes"
     chef.cookbooks_path = ["./", "./cookbooks", "./site-cookbooks"]
     chef.add_recipe "apt"
     chef.add_recipe "gin_and_bitters"
  end
end
