---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.19.36

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[martini::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
