include_recipe 'negroni::setup_package'
include_recipe 'negroni::setup_application'
include_recipe 'negroni::setup_repository'
include_recipe 'negroni::setup_middleware'
include_recipe 'negroni::setup_delayed-job'
include_recipe 'negroni::setup_swap'