---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[gin_and_bitters::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
