---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.19.36

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[gin_and_bitters::default]
#      - recipe[gin_and_bitters::setup]
#      - recipe[gin_and_bitters::setup_docker-env]
#      - recipe[gin_and_bitters::setup_vagrant-env]
#      - recipe[gin_and_bitters::setup_aws-env]
#      - recipe[gin_and_bitters::setup_heroku-env]
#      - recipe[gin_and_bitters::setup_jenkins-env]
#      - recipe[gin_and_bitters::setup_emacs-env]
#      - recipe[gin_and_bitters::setup_chef-server-env]
#      - recipe[gin_and_bitters::configure]

    verifier:
      inspec_tests:
        - test/recipes
    attributes:
