name 'gin_and_bitters'
maintainer 'Hiroshima ARC'
maintainer_email 'hiroshima.arc@gmail.com'
license 'all_rights'
description 'Installs/Configures martini'
long_description 'Installs/Configures martini'
version '0.3.0'

depends 'apt',    '2.9.2'
depends 'git', '~> 5.0.1'
depends 'curl', '~> 2.0.3'
depends 'docker', '~> 2.0'
depends 'docker_compose', '~> 0.0'
depends 'vagrant', '~> 0.7.0'
depends 'chef-dk','~> 3.0.0'
depends 'python', '~> 1.4.6'
depends 'awscli', '~> 1.1.2'
depends 'aws',    '~> 2.7.2'
depends 'terraform', '~> 0.5.1'
depends 'jenkins', '~> 3.1.0'
depends 'poise-ruby', '~> 2.2.0'
depends 'heroku', '~> 0.1.0'
depends 'emacs24', '~> 0.5.0'
depends 'packer', '~> 0.4.0'
depends 'vagrant', '~> 0.7.0'